<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Update</name>
   <tag></tag>
   <elementGuidId>538678e6-f21f-42d6-8919-407cf7317cf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ant-col.ant-col-5 > button.ant-btn.ant-btn-default.button__DefaultButton-yvt5em-0.button__SecondaryButton-yvt5em-2.dwrfPO.jxDBgY</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[63]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>11548049-f6f8-4000-aa22-ad150dfb2ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fbc6fb0c-c9a4-4923-9893-2b4eb1b4d2d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn ant-btn-default button__DefaultButton-yvt5em-0 button__SecondaryButton-yvt5em-2 dwrfPO jxDBgY</value>
      <webElementGuid>b491c34f-9ede-4dc2-ae2b-9d5bce4f92d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Update</value>
      <webElementGuid>2cacd8b9-d4f1-45f0-923e-b651bc714ef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[4]/div[@class=&quot;ant-modal-root&quot;]/div[@class=&quot;ant-modal-wrap ant-modal-centered&quot;]/div[@class=&quot;ant-modal modal__PrimaryModal-sc-1kexpe2-0 efvkWW&quot;]/div[@class=&quot;ant-modal-content&quot;]/div[@class=&quot;ant-modal-body&quot;]/div[@class=&quot;ant-row ant-row-center ant-row-middle indexstyle__UploadButtonWrapper-s3h3fy-3 gEHPpU&quot;]/div[@class=&quot;ant-col ant-col-5&quot;]/button[@class=&quot;ant-btn ant-btn-default button__DefaultButton-yvt5em-0 button__SecondaryButton-yvt5em-2 dwrfPO jxDBgY&quot;]</value>
      <webElementGuid>08894c35-77c4-4a71-a39b-ba681f34b8bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[63]</value>
      <webElementGuid>acd1953a-67a7-4b27-8274-1faf5b7f6cb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>d5ddfe84-3d03-46f8-b3f4-619effca3896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prostate Biopsy'])[24]/following::button[3]</value>
      <webElementGuid>b9b6954b-09c6-494d-a46d-905b94e2bd14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>74701a81-164e-4fdd-b029-4f38a00a9316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Update' or . = 'Update')]</value>
      <webElementGuid>67425500-fac6-4de5-bb1f-b84e096a816c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
