<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>1a5ac3ea-cb62-40bd-8fd0-3bd36e5721cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='People'])[1]/following::div[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ant-select-selection-overflow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>878db5ef-bdcb-4a3e-9e93-857b721ae0f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-select-selection-overflow</value>
      <webElementGuid>995f24ef-1818-4bfb-a7ca-0c3e23c602ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>b54a705c-e8aa-41f7-a5de-905d7d0c86b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[4]/div[@class=&quot;ant-modal-root&quot;]/div[@class=&quot;ant-modal-wrap ant-modal-centered&quot;]/div[@class=&quot;ant-modal modal__PrimaryModal-sc-1kexpe2-0 efvkWW&quot;]/div[@class=&quot;ant-modal-content&quot;]/div[@class=&quot;ant-modal-body&quot;]/div[@class=&quot;ant-row indexstyle__SearchInputWrapper-oj3o8u-1 gNkUvd&quot;]/div[@class=&quot;ant-col ant-col-19&quot;]/div[@class=&quot;indexstyle__SearchContiner-sc-1w8qnri-3 ccyruF&quot;]/div[@class=&quot;ant-select indexstyle__SelectInputWrapper-sc-1w8qnri-0 gQxzhS ant-select-multiple ant-select-open ant-select-show-search&quot;]/div[@class=&quot;ant-select-selector&quot;]/div[@class=&quot;ant-select-selection-overflow&quot;]</value>
      <webElementGuid>7fc0f4ff-5395-43f7-b41b-b80a97211a59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='People'])[1]/following::div[7]</value>
      <webElementGuid>c692cfcf-32ad-4825-bc69-157ade6ab297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Share Access - ', '&quot;', 'Case No. PL-0005', '&quot;', '')])[1]/following::div[10]</value>
      <webElementGuid>8e3f10ae-ec36-4d86-931a-89293a2a8719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find and add people in your workspace'])[1]/preceding::div[3]</value>
      <webElementGuid>30500631-040e-4aad-a8dc-b4a8f14c2f26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share'])[1]/preceding::div[3]</value>
      <webElementGuid>3433599b-2e6e-4687-b3a4-935caa9f3836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[2]/div/div</value>
      <webElementGuid>258bbb8f-110c-46cf-83fc-eac5416828ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' ' or . = ' ')]</value>
      <webElementGuid>f07c72bd-a1d2-4355-8e93-e8ee176ebc41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
