<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Hi, Vrushali D</name>
   <tag></tag>
   <elementGuidId>c79a6422-0025-4344-a125-18b51d355f39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/section/header/div/div[2]/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.indexstyle__UserNameContainer-sc-10scot-9.YEGHh > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>22bf18ba-03f7-43a3-934d-75ed9d90e5e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hi, Vrushali D</value>
      <webElementGuid>9ab5eb60-245e-4a7b-8817-11db8e7f5c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;ant-space ant-space-vertical indexstyle__SpaceWrapper-sc-1gsl3no-0 erfuCE&quot;]/div[@class=&quot;ant-space-item&quot;]/section[@class=&quot;ant-layout indexstyle__LayoutWrapper-sc-1gsl3no-1 huUvf&quot;]/header[@class=&quot;ant-layout-header indexstyle__HeaderWrapper-sc-10scot-0 insbUX&quot;]/div[@class=&quot;ant-row ant-row-middle indexstyle__HeaderRowWrapper-sc-10scot-6 dmstUo&quot;]/div[@class=&quot;ant-col ant-col-12&quot;]/div[@class=&quot;indexstyle__AccountContainer-sc-10scot-3 wHyAY&quot;]/div[@class=&quot;indexstyle__DropDownContainer-sc-10scot-7 iCDAOa&quot;]/div[@class=&quot;indexstyle__UserAvatarContainer-sc-10scot-8 bJNPLJ ant-dropdown-trigger&quot;]/div[@class=&quot;indexstyle__UserNameContainer-sc-10scot-9 YEGHh&quot;]/div[1]</value>
      <webElementGuid>136f9cb8-2b21-4660-85f7-a072b51e9f52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/section/header/div/div[2]/div/div/div/div/div</value>
      <webElementGuid>707e8aeb-5334-49aa-8f0a-f7e4c26cd298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PANTHEON'])[1]/following::div[6]</value>
      <webElementGuid>ff7f559d-e069-4d67-bddc-8291fa749452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CASES'])[1]/preceding::div[2]</value>
      <webElementGuid>453f20e0-8bf7-4a0d-9a77-c30a9a294b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ Create New Case'])[1]/preceding::div[14]</value>
      <webElementGuid>dd9b16a9-0627-4851-8bb4-b6d9b9a4b999</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hi,']/parent::*</value>
      <webElementGuid>a0d5e320-a9f3-453a-a028-55434ddc57df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div</value>
      <webElementGuid>c5a8b139-33e9-42b5-ad6a-54741b87673c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Hi, Vrushali D' or . = 'Hi, Vrushali D')]</value>
      <webElementGuid>e5792250-76e0-4c13-b117-5b01fc175b8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
