<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Analyse_indexstyle__StyledSlideImage-kh_5ddf3f</name>
   <tag></tag>
   <elementGuidId>6d0e3ea6-100c-4233-b72a-fadaa29d3dc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-tabs-1-panel-PATHOLOGY_SLIDES']/div/div[2]/div/div/div/div/div/table/tbody/tr[3]/td[2]/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.indexstyle__StyledSlideImage-khit8p-6.fPBlgl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>94a26c93-b25c-4dae-8a02-ca2d6152b3b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://pl-qa-pantheon-mock.eks.qritive.com/api/v1/tile/thumbnail?resourceId=65128c5bc6085ef55efe652e&amp;filePath=PL-0050/PL-0050-03/PL-0050-03&amp;width=160&amp;height=100</value>
      <webElementGuid>04220096-bb63-4f75-9872-d2bde03b10d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Not Available</value>
      <webElementGuid>14b3bb79-8dc1-473d-b871-0b8278a9c8b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>slide-file-thumbnail</value>
      <webElementGuid>7264d788-5193-4d03-9f67-db33e297f50d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>b5e44c92-7068-4575-a0c9-710d28461fb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>32c879f5-831f-438b-99f5-4d0c5b967dff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>indexstyle__StyledSlideImage-khit8p-6 fPBlgl</value>
      <webElementGuid>47aed2cb-dfd7-4d83-9f6d-7b86976515c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-tabs-1-panel-PATHOLOGY_SLIDES&quot;)/div[@class=&quot;indexstyle__Container-khit8p-0 cabjrC&quot;]/div[@class=&quot;ant-table-wrapper&quot;]/div[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;ant-table&quot;]/div[@class=&quot;ant-table-container&quot;]/div[@class=&quot;ant-table-content&quot;]/table[1]/tbody[@class=&quot;ant-table-tbody&quot;]/tr[@class=&quot;ant-table-row ant-table-row-level-0&quot;]/td[@class=&quot;ant-table-cell ant-table-cell-row-hover&quot;]/div[@class=&quot;indexstyle__SlideImageWrapper-khit8p-9 jgRFtA&quot;]/img[@class=&quot;indexstyle__StyledSlideImage-khit8p-6 fPBlgl&quot;]</value>
      <webElementGuid>9e5f38bd-ad7b-4898-b76f-184a62e307a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-tabs-1-panel-PATHOLOGY_SLIDES']/div/div[2]/div/div/div/div/div/table/tbody/tr[3]/td[2]/div/img</value>
      <webElementGuid>24361f28-703d-42ce-ace4-430bb38bf552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Not Available'])[3]</value>
      <webElementGuid>8b6b3649-2e36-4cc9-905f-7ea57bebb65b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/div/img</value>
      <webElementGuid>2b2edf1c-b433-49f7-831b-851de596ad7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://pl-qa-pantheon-mock.eks.qritive.com/api/v1/tile/thumbnail?resourceId=65128c5bc6085ef55efe652e&amp;filePath=PL-0050/PL-0050-03/PL-0050-03&amp;width=160&amp;height=100' and @alt = 'Not Available']</value>
      <webElementGuid>86bc8117-599a-49ab-9da6-1bc124edea01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
