<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_ant-input</name>
   <tag></tag>
   <elementGuidId>33ea9e17-a575-49d0-8f29-1cba00460574</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ant-input-affix-wrapper.ant-input-affix-wrapper-focused.ant-input-password.style__PasswordInputWrapper-jdeaeh-2.ghKjyO.ant-input-affix-wrapper-status-success > input.ant-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='V']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2b202b40-4f54-463b-8ca4-08108b8cf69d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Password</value>
      <webElementGuid>79542e79-bdd3-4c02-bcd4-33310dc0b12c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>b6c82c76-ecef-476c-9f98-a564115e00bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input</value>
      <webElementGuid>01480e80-113a-4a47-a531-d5eea1b5ebe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signUpEmail&quot;)/div[@class=&quot;ant-form-item indexstyle__PasswordFormWrapper-sc-3gh0vu-7 dIHcDc ant-form-item-has-success&quot;]/div[@class=&quot;ant-row ant-form-item-row&quot;]/div[@class=&quot;ant-col ant-form-item-control&quot;]/div[@class=&quot;ant-form-item-control-input&quot;]/div[@class=&quot;ant-form-item-control-input-content&quot;]/div[@class=&quot;style__PasswordInputContainer-jdeaeh-0 bmViPQ&quot;]/span[@class=&quot;ant-input-affix-wrapper ant-input-affix-wrapper-focused ant-input-password style__PasswordInputWrapper-jdeaeh-2 ghKjyO ant-input-affix-wrapper-status-success&quot;]/input[@class=&quot;ant-input&quot;]</value>
      <webElementGuid>edfd7a59-a989-4a07-89f8-6c112cad6da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>V</value>
      <webElementGuid>0a8d91de-4053-46dc-a664-6ba7b4d29a2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='V']</value>
      <webElementGuid>70fd1a84-7839-4407-ab94-f3d8f43e067d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signUpEmail']/div[2]/div/div/div/div/div/span/input</value>
      <webElementGuid>33abbc68-8126-47c8-9680-75d990996422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>b821c074-748c-4b9a-976a-313a6e04a368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Password' and @type = 'password']</value>
      <webElementGuid>f38ec9de-66b0-4928-b85d-af93060ac8ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Q']</value>
      <webElementGuid>cd677bf6-db1e-4603-a254-247dcab85ca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>1dbc1cba-59d9-4997-8819-b374c9259165</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
