<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_ant-input style__TextInputWrapp_ced313</name>
   <tag></tag>
   <elementGuidId>f57ed4aa-406e-4c9e-a2cb-a0cc1c6d496c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.ant-input.ant-input-status-success.style__TextInputWrapper-sc-11t5rbb-3.hERMmn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;patientInfo&quot;]/div[1]/div/div/div/div/div/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3d43e594-8391-407e-a6bf-e1ff2162fa07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7ff48bf2-b219-4ce7-871d-7944a83ef261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Patient Name</value>
      <webElementGuid>025b6c6c-5c51-4c46-b480-3917fc978b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-status-success style__TextInputWrapper-sc-11t5rbb-3 hERMmn</value>
      <webElementGuid>4568e2bf-9eb8-4b6e-bdcf-4c7d82af4e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;patientInfo&quot;)/div[@class=&quot;ant-form-item indexstyle__PatientFormItem-sc-1mzvaed-1 czmtgB ant-form-item-has-success&quot;]/div[@class=&quot;ant-row ant-form-item-row&quot;]/div[@class=&quot;ant-col ant-form-item-control&quot;]/div[@class=&quot;ant-form-item-control-input&quot;]/div[@class=&quot;ant-form-item-control-input-content&quot;]/div[@class=&quot;ant-row ant-row-middle&quot;]/div[@class=&quot;ant-col ant-col-19&quot;]/input[@class=&quot;ant-input ant-input-status-success style__TextInputWrapper-sc-11t5rbb-3 hERMmn&quot;]</value>
      <webElementGuid>666a25cf-7686-4ad5-b3cd-d777c52da0c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>isyntax Prostate</value>
      <webElementGuid>b820a738-3ee9-4c89-8963-e783f6f06a3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='isyntax Prostate']</value>
      <webElementGuid>dbe61f2c-c8b4-42d6-b538-75c683d9e4c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='patientInfo']/div/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>1237d161-05fe-4cfa-b789-647e1217b686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e676f9c3-6f32-4f04-8b80-8c736d18cceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Patient Name' and @type = 'text']</value>
      <webElementGuid>1203d351-5ac5-4e2f-b6cd-31aae9663b3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>4f5d62f6-4192-4915-a9c2-6dd2db3bf767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signUpEmail']/div/div/div/div/div/div/input</value>
      <webElementGuid>2b56d7ea-0219-4758-8416-7ce22a154e80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Enter email']</value>
      <webElementGuid>04def93d-d2e8-487b-9b57-f9bdfce17b8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[4]</value>
      <webElementGuid>4312abd6-4ddc-4d5c-9cf6-cd5087c465b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-tabs-1-panel-PATHOLOGY_SLIDES']/div/div[2]/div/div/div/div/div/table/tbody/tr/td/label/span/input</value>
      <webElementGuid>3c41f6cf-f974-4dfb-875f-a14369340044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/label/span/input</value>
      <webElementGuid>d6e8096d-f40b-46d0-8fb7-16c066c04db6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>c94ad008-9e88-44d6-8037-8b9a20f46408</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
